"use client";

import { useState, useEffect } from "react";
import Markdown from "react-markdown";

interface Props { message: { id?: string; role: "user" | "assistant"; content: string }; isLoading?: boolean; isThinking?: boolean; model?: string; }
const stages = ["Thinking", "Connecting the dots", "Writing a clear answer"];

export function MessageBubble({ message, isLoading, isThinking }: Props) {
  const [stage, setStage] = useState(0);
  useEffect(() => { if (!isThinking) return; const timer = window.setInterval(() => setStage((value) => (value + 1) % stages.length), 1800); return () => window.clearInterval(timer); }, [isThinking]);
  if (message.role === "user") return <div className="flex justify-end animate-slide-up"><div className="max-w-[82%] rounded-2xl rounded-br-md bg-[#18212f] px-4 py-3 text-sm leading-6 text-white shadow-[0_8px_24px_rgba(24,33,47,.12)]">{message.content}</div></div>;
  return <div className="flex gap-3 animate-slide-up"><img src="/logo.svg" alt="" className="h-8 w-8 shrink-0 rounded-xl border border-[#e0e5ed] bg-white p-1" /><div className="min-w-0 flex-1"><div className="mb-1 text-[11px] font-semibold uppercase tracking-[.12em] text-[#8390a3]">Soop AI</div>{isLoading && isThinking && !message.content ? <div className="inline-flex items-center gap-2 rounded-2xl rounded-tl-md border border-[#e2e6ec] bg-[#f7f8fa] px-4 py-3 text-xs text-[#718198]"><span className="flex gap-1"><i className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#4662f0]" /><i className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#4662f0] [animation-delay:200ms]" /><i className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#4662f0] [animation-delay:400ms]" /></span>{stages[stage]}</div> : <div className="rounded-2xl rounded-tl-md border border-[#e2e6ec] bg-white px-4 py-3 text-sm leading-7 text-[#334155] shadow-[0_5px_18px_rgba(35,48,70,.04)]"><MarkdownContent content={message.content} />{isLoading && <span className="ml-1 inline-block h-4 w-0.5 animate-pulse bg-[#4662f0] align-text-bottom" />}</div>}</div></div>;
}

function MarkdownContent({ content }: { content: string }) { return <Markdown components={{ p: ({ children }) => <p className="mb-3 last:mb-0">{children}</p>, h1: ({ children }) => <h1 className="mb-3 mt-5 text-xl font-semibold text-[#18212f]">{children}</h1>, h2: ({ children }) => <h2 className="mb-2 mt-4 text-lg font-semibold text-[#18212f]">{children}</h2>, ul: ({ children }) => <ul className="mb-3 list-disc space-y-1 pl-5">{children}</ul>, ol: ({ children }) => <ol className="mb-3 list-decimal space-y-1 pl-5">{children}</ol>, li: ({ children }) => <li>{children}</li>, strong: ({ children }) => <strong className="font-semibold text-[#18212f]">{children}</strong>, a: ({ href, children }) => <a href={href} target="_blank" rel="noreferrer" className="font-medium text-[#3857e8] underline-offset-2 hover:underline">{children}</a>, code({ className, children, ...props }) { const match = /language-(\w+)/.exec(className || ""); if (!match) return <code className="rounded-md bg-[#eef1f5] px-1.5 py-0.5 text-[12px] text-[#4b5563]" {...props}>{children}</code>; const code = String(children).replace(/\n$/, ""); return <div className="my-4 overflow-hidden rounded-xl border border-[#dfe4eb] bg-[#f7f8fa]"><div className="flex items-center justify-between border-b border-[#dfe4eb] px-3 py-2 text-[11px] font-medium uppercase tracking-[.1em] text-[#8290a3]"><span>{match[1]}</span><CopyButton text={code} /></div><pre className="overflow-x-auto px-4 py-3 text-[13px] leading-6 text-[#334155]"><code>{code}</code></pre></div>; } }}>{content}</Markdown>; }
function CopyButton({ text }: { text: string }) { const [copied, setCopied] = useState(false); return <button onClick={async () => { await navigator.clipboard.writeText(text); setCopied(true); window.setTimeout(() => setCopied(false), 1400); }} className="rounded-md bg-white px-2 py-1 text-[10px] font-medium normal-case tracking-normal text-[#718198] hover:text-[#18212f]">{copied ? "Copied" : "Copy"}</button>; }
